name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
      
jobs:
  cargo_watch:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install cargo-watch
        run: cargo install cargo-watch

      - name: Run cargo watch
        run: cargo watch -x check
        
  backend:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    needs: [cargo_watch]
    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory : backend/
      run: cargo watch -q -c -w src/ -x run
      
  client_side:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    needs: [backend]
    steps:
    - uses: actions/checkout@v3
    - name: Test
      working-directory : backend/
      run: cargo watch -q -c -w tests/ -x "test -q quick_dev -- --nocapture"
