name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
      
jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
      
    - name: Build
      working-directory : backend/
      run: cargo build --package backend --bin backend

    - name: Tests
      working-directory : backend/
      run: cargo test --package backend --test test -- test_post_request --exact --nocapture 
