name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
      
jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
      
    - name: Build
      working-directory : backend/
      run: cargo build --verbose

    - name: Tests
      working-directory : backend/
      run: cargo test --verbose
    
    - name: Clippy
      working-directory : backend/
      run: cargo clippy --verbose -- -D warnings

    - name: Audit
      working-directory : backend/
      run: |
        cargo install cargo-audit 
        cargo audit 